### ISSUE TITLE
您好，我运行demo.py的时候，显示如下，网上说batchsize太大，但是我找到不到运行demo.py调整batchsize的地方？

### ISSUE THREAD

**Issue by Linda-L** [jianzhnie/pyramidbox_pytorch#4]
/home/lyl/anaconda3/envs/py1.3/bin/python /home/lyl/000_Code/pyramidbox_1.3/demo.py
Traceback (most recent call last):
  File "/home/lyl/000_Code/pyramidbox_1.3/demo.py", line 113, in <module>
    detect(net, path, args.thresh)
  File "/home/lyl/000_Code/pyramidbox_1.3/demo.py", line 73, in detect
    y = net(x)
  File "/home/lyl/anaconda3/envs/py1.3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyl/000_Code/pyramidbox_1.3/models/pyramidbox.py", line 173, in forward
    ssh_conv3_norm = self.cpm[0](self.L2Norm3_3(lfpn0_on_conv3))
  File "/home/lyl/anaconda3/envs/py1.3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyl/000_Code/pyramidbox_1.3/models/pyramidbox.py", line 56, in forward
    out_residual = self.branch1(x)
  File "/home/lyl/anaconda3/envs/py1.3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyl/000_Code/pyramidbox_1.3/models/pyramidbox.py", line 35, in forward
    return self.bn1(x)
  File "/home/lyl/anaconda3/envs/py1.3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyl/anaconda3/envs/py1.3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/lyl/anaconda3/envs/py1.3/lib/python3.6/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 322.00 MiB (GPU 0; 3.95 GiB total capacity; 2.90 GiB already allocated; 88.56 MiB free; 39.48 MiB cached)

Process finished with exit code 1

**Comment by jianzhnie** [comment]
或许是你的电脑现存太小了，我在8G显存的电脑运行是OK的
